Repository palantir/assertj-automation, pull requests merged in 2020-02, with the labels that each got.

#46 Support JUnit5 in PreferAssertJ
  assertj-error-prone/src/main/java/com/palantir/assertj/errorprone/PreferAssertj.java
  assertj-error-prone/src/test/java/com/palantir/assertj/errorprone/PreferAssertjTests.java
  changelog/@unreleased/pr-46.v2.yml
Labels: autorelease, merge when ready

#49 Remove JUnit5 fail static import
  assertj-error-prone/src/main/java/com/palantir/assertj/errorprone/PreferAssertj.java
  changelog/@unreleased/pr-49.v2.yml
Labels: autorelease, merge when ready

#54 Add test for removing JUnit5 fail static import
  assertj-error-prone/src/test/java/com/palantir/assertj/errorprone/PreferAssertjTests.java
Labels: merge when ready, no changelog

#70 Add check for replacing try-catch-fail with assertThatThrownBy
  assertj-error-prone/src/main/java/com/palantir/assertj/errorprone/AssertjAssertThatThrownBy.java
  assertj-error-prone/src/test/java/com/palantir/assertj/errorprone/AssertjAssertThatThrownByTest.java
  build.gradle
  changelog/@unreleased/pr-70.v2.yml
Labels: autorelease, merge when ready

#78 AssertjAssertThatThrownBy preserves 'try {' comments
  assertj-error-prone/src/main/java/com/palantir/assertj/errorprone/AssertjAssertThatThrownBy.java
  assertj-error-prone/src/test/java/com/palantir/assertj/errorprone/AssertjAssertThatThrownByTest.java
  changelog/@unreleased/pr-78.v2.yml
Labels: merge when ready
